### PR TITLE
Repo tidying and AWS setup

### PR DESCRIPTION
**Pull request by ian-ross**
Bring image processing code into tasks repository from fp-legacy and fold into a single Docker image.  Changes for deployment on AWS.

### CODE REVIEW

**Comment by sethfitz** [comment]
Can you split the AWS deployment changes out?

I'd rather not fold the image processing code in, partly because we'd like to retire it sometime in the next 6 months.

**Comment by ian-ross** [comment]
Will do.  I had mostly been thinking about folding the image processing stuff in for ease of debugging.  I had a couple of cases where I was trying to get things working on AWS and needed to add some debug output to the image processing code (in the end it turns out to be a memory issue and things just getting killed by CloudFormation, but it was hard to debug that from the output I could see).  That meant building and pushing the `fp-legacy/decoder` Docker image, then building and pushing the `fp-tasks` Docker image, then pulling the `fp-tasks` image on the EC2 instance and restarting things.  There has to be a better workflow for this sort of thing, but I couldn't figure one out, so ended up pulling the image processing stuff in.  I'll take it out and just make a PR for the AWS-related changes.

**Comment by sethfitz** [comment]
Agreed, let's keep looking for a better way to deal with this.

Thanks!

**Comment by ian-ross** [comment]
I've now descoped this to just include the changes to the S3 endpoint processing to work with non-default AWS regions.

Please don't merge it until I've made sure that I've got all the default and non-default region stuff for S3 working in `fp-web`.  I'll do that next and let you know when it's good to go!

**Comment by sethfitz** [comment]
Great!

**Comment by ian-ross** [comment]
By the way, this PR should also be good to merge now -- it's the task manager bit of the AWS setup.  It's just non-default region S3 URL fixups.

**Comment by sethfitz** [comment]
Do you need/want an updated Docker image for this, or can it wait until other improvements land?

**Comment by ian-ross** [comment]
No need for a new image yet.  Let's wait for the dust to settle.  I get the feeling that Field Papers is going to be seeing quite a lot of attention over the next couple of months!

**Pull request merged**
